let storeBlacklist = [
  'zoom',
  'vivo',
  'tiendamia.com.br',
  'olx',
  'techinn.com',
  'alifone.com.br',
  'buscapé',
  'ar free comercio',
  'loja tim',
  'top comercio de moveis',
  'trocafone marketplace br',
  'outlet do celular',
  'saldão da informática',
  'ri happy brinquedos',
  'machado moveis e eletros',
  'casa guararapes comercial eireli',
  'webfones',
  'madeiramadeira',
  'melo e lopes comércio',
  'Pet shop rosa',
  'Lojas Presidente',
  'Imperial Centers',
  'Melhor Ofertas Magazine',
  'Melhor Comprar',
  'Fujioka',
  'shopp magazinnee online',
  'Super Ofertas Magazine',
  'ameriican natal',
  'Infinity eletroshopping',
  'TudoOnline',
  'Varejoo Compras',
  'Comercio Magallu',
  'Shoop Tiimee Online 2022',
  'Virtual On Magazine',
  'Romario Variedades'
];

storeBlacklist = storeBlacklist.map(item => item.toLowerCase())

export {storeBlacklist}
